/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mundialf1.Interfaces;

import mundialf1.Clases.Mundial;
import mundialf1.Clases.ModeloTabla;
import mundialf1.Renderer.NacionalidadRenderer;
import mundialf1.Renderer.NombreRenderer;
import mundialf1.Renderer.PuntosRenderer;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import mundialf1.Clases.Escuderia;
import mundialf1.Clases.GestionMovimientos;

import mundialf1.Renderer.DateRenderer;

/**
 *
 * @author usuario
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    ModeloTabla modelo = new ModeloTabla();
    Escuderia escuderia = new Escuderia();

    public Main() {
        initComponents();

        //Asignar la lista de datos a la tabla
        modelo.setDataList(list1);
        jTable1.setModel(modelo);
        //Sólo se permite seleccionar un registro
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Detectar cambio de selección en la tabla

        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int indiceFilaSeleccionada = jTable1.getSelectedRow();
                if (indiceFilaSeleccionada != -1) {
                    Mundial mundial = new Mundial();
                    mundial = list1.get(indiceFilaSeleccionada);
                    panelF11.setMundial(mundial);
                    panelF11.showData();
                }
            }

        });
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new DateRenderer());
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new PuntosRenderer());
        jTable1.getColumnModel().getColumn(0).setCellRenderer(new NombreRenderer());
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new NacionalidadRenderer());

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(156);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(67);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(82);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(58);

        //Sólo se permite seleccionar un registro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("MundialF1PU").createEntityManager();
        query1 = java.beans.Beans.isDesignTime() ? null : entityManager1.createQuery("SELECT m FROM Mundial m");
        list1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : query1.getResultList();
        jTabbedPaneDatos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        panelF11 = new mundialf1.Interfaces.PanelF1();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonPiloto = new javax.swing.JButton();
        jButtonTabla = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPaneDatos.setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jTable1.setBackground(new java.awt.Color(237, 253, 254));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneDatos.addTab("Tabla", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        panelF11.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelF11, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(panelF11, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jTabbedPaneDatos.addTab("Pilotos", jPanel2);

        getContentPane().add(jTabbedPaneDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 204));
        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonPiloto.setBackground(new java.awt.Color(255, 255, 204));
        jButtonPiloto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/blue-user-icon.png"))); // NOI18N
        jButtonPiloto.setText("Info Piloto");
        jButtonPiloto.setFocusable(false);
        jButtonPiloto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPiloto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilotoActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonPiloto);

        jButtonTabla.setBackground(new java.awt.Color(255, 255, 204));
        jButtonTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/blue-address-book-icon.png"))); // NOI18N
        jButtonTabla.setText("Tabla");
        jButtonTabla.setFocusable(false);
        jButtonTabla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTabla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTablaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonTabla);

        jButtonInsertar.setBackground(new java.awt.Color(255, 255, 204));
        jButtonInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/blue-document-plus-icon.png"))); // NOI18N
        jButtonInsertar.setText("Insertar");
        jButtonInsertar.setFocusable(false);
        jButtonInsertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInsertar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonInsertar);

        jButtonActualizar.setBackground(new java.awt.Color(255, 255, 204));
        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/blue-document-icon.png"))); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.setFocusable(false);
        jButtonActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonActualizar);

        jButtonEliminar.setBackground(new java.awt.Color(255, 255, 204));
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/blue-document-cross-icon.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setActionCommand("");
        jButtonEliminar.setFocusable(false);
        jButtonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonEliminar);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 350, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        String texto = "Se ha insertado: ";
        Mundial mundial = panelF11.newMundial();
        if (panelF11.checkMundial()) {
            entityManager1.getTransaction().begin();
            //Almacenar el objeto en la BD
            entityManager1.persist(mundial);
            entityManager1.getTransaction().commit();

            //Añadir el objeto al final de la lista de datos
            list1.add(mundial);
            texto += mundial.getNombrePiloto();
            
            texto += " en el registro.";
            //Informar al JTable que se ha insertado una fila al final
            modelo.fireTableRowsInserted(list1.size() - 1, list1.size() - 1);
        } else {
            JOptionPane.showMessageDialog(this, "Debe introducir algún dato para continuar.");
        }

        GestionMovimientos gestionMovimientos = new GestionMovimientos();
        gestionMovimientos.escribirArchivo(texto);

    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        //Obtener el índice de la fila seleccionada en la tabla
        int selectedRow = jTable1.getSelectedRow();
        //Obtener el objeto desde la lista de datos, conociendo su posición
        Mundial mundial = list1.get(selectedRow);

        //Iniciar una transacción con la BD
        entityManager1.getTransaction().begin();
        //Eliminar el objeto
        entityManager1.remove(mundial);
        //Finalizar la transacción actualizando la BD
        entityManager1.getTransaction().commit();

        //Eliminar el objeto de la lista de datos
        list1.remove(mundial);
        //Informar al JTable que se ha eliminado una fila
        modelo.fireTableRowsDeleted(selectedRow, selectedRow);
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        //Obtener el índice de la fila seleccionada en la tabla 
        int selectedRow = jTable1.getSelectedRow();
//Obtener el objeto desde la lista de datos, conociendo su posición 
        Mundial mundial = list1.get(selectedRow);
        //Rellenar sus datos 

        entityManager1.getTransaction().begin();
//Actualizar el objeto en la BD 
        entityManager1.merge(mundial);
        entityManager1.getTransaction().commit();

//Añadir el objeto al final de la lista de datos 
        list1.set(selectedRow, mundial);
//Informar al JTable que se ha modificado la fila seleccionada 
        modelo.fireTableRowsUpdated(selectedRow, selectedRow);
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilotoActionPerformed
        jTabbedPaneDatos.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonPilotoActionPerformed

    private void jButtonTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTablaActionPerformed
        jTabbedPaneDatos.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonPiloto;
    private javax.swing.JButton jButtonTabla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneDatos;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private java.util.List<Mundial> list1;
    private mundialf1.Interfaces.PanelF1 panelF11;
    private javax.persistence.Query query1;
    // End of variables declaration//GEN-END:variables
}
